# run: conda env create --file environment.yml
# optionally, change channel name with -n {plantcv-dev}
name: plantcv
dependencies:
  - python=3.9
  - matplotlib>=1.5
  - numpy>=1.11
  - pandas
  - python-dateutil
  - scipy
  - scikit-image>=0.13
  - scikit-learn
  - plotnine
  - dask
  - dask-jobqueue
  - nb_conda
  - opencv
  - statsmodels
  - xarray
  - mkdocs
  - pytest
channels:
  - conda-forge
  - defaults
